version: '2'
services:
  webserver:
    build:
      context: ./
      dockerfile: webserver-prod.dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - database.env
  db:
    build:
      context: ./
      dockerfile: database.dockerfile
    env_file:
      - database.env
